from dataclasses import dataclass
import enum
from typing import Optional, Tuple


class EquipmentType(enum.Enum):
    ARMOR = 0
    WEAPON = 1


@dataclass(frozen=True)
class Material:
    item_id: str
    amount: int


@dataclass(frozen=True)
class Enhancement:
    item_id: str
    rate_increase_permyria: int
    max_amount: int


@dataclass(frozen=True)
class HoningLevel:
    base_item_level: int
    next_item_level: int
    tier: int
    base_level: int
    equipment_type: EquipmentType
    base_rate_permyria: int
    bonus_rate_permyria: int
    research_bonus_permyria: int
    cost: Tuple[Material, ...]
    enhancements: Tuple[Enhancement, ...] = ()
    max_enhancement_rate_permyria: int = 0
    book_id: Optional[str] = None


HONES = (
    # ----- Low T3 (1302-1370) -----
    HoningLevel(
        base_item_level=1302,
        next_item_level=1304,
        tier=3,
        base_level=0,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=10000,
        bonus_rate_permyria=0,
        research_bonus_permyria=0,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=41),
            Material(item_id='honor-leapstone-2', amount=1),
            Material(item_id='honor-shard', amount=11),
            Material(item_id='silver', amount=5550),
        ),
    ),
    HoningLevel(
        base_item_level=1304,
        next_item_level=1307,
        tier=3,
        base_level=1,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=10000,
        bonus_rate_permyria=0,
        research_bonus_permyria=0,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=41),
            Material(item_id='honor-leapstone-2', amount=1),
            Material(item_id='honor-shard', amount=11),
            Material(item_id='silver', amount=4590),
        ),
    ),
    HoningLevel(
        base_item_level=1307,
        next_item_level=1310,
        tier=3,
        base_level=2,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=10000,
        bonus_rate_permyria=0,
        research_bonus_permyria=0,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=41),
            Material(item_id='honor-leapstone-2', amount=2),
            Material(item_id='honor-shard', amount=11),
            Material(item_id='silver', amount=5830),
        ),
    ),
    HoningLevel(
        base_item_level=1310,
        next_item_level=1315,
        tier=3,
        base_level=3,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=10000,
        bonus_rate_permyria=0,
        research_bonus_permyria=0,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=60),
            Material(item_id='honor-leapstone-2', amount=2),
            Material(item_id='simple-oreha-fusion-material-1', amount=1),
            Material(item_id='honor-shard', amount=16),
            Material(item_id='silver', amount=5980),
        ),
    ),
    HoningLevel(
        base_item_level=1315,
        next_item_level=1320,
        tier=3,
        base_level=4,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=10000,
        bonus_rate_permyria=0,
        research_bonus_permyria=0,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=60),
            Material(item_id='honor-leapstone-2', amount=2),
            Material(item_id='simple-oreha-fusion-material-1', amount=1),
            Material(item_id='honor-shard', amount=16),
            Material(item_id='silver', amount=6120),
        ),
    ),
    HoningLevel(
        base_item_level=1320,
        next_item_level=1325,
        tier=3,
        base_level=5,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=10000,
        bonus_rate_permyria=0,
        research_bonus_permyria=0,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=60),
            Material(item_id='honor-leapstone-2', amount=2),
            Material(item_id='simple-oreha-fusion-material-1', amount=1),
            Material(item_id='honor-shard', amount=16),
            Material(item_id='silver', amount=6270),
        ),
    ),
    HoningLevel(
        base_item_level=1325,
        next_item_level=1330,
        tier=3,
        base_level=6,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=6000,
        bonus_rate_permyria=2000,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=78),
            Material(item_id='honor-leapstone-2', amount=2),
            Material(item_id='simple-oreha-fusion-material-1', amount=1),
            Material(item_id='honor-shard', amount=21),
            Material(item_id='silver', amount=6420),
            Material(item_id='gold', amount=35),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=125,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=250,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=750,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=4000,
        book_id='tailoring-basic-mending-3',
    ),
    HoningLevel(
        base_item_level=1330,
        next_item_level=1335,
        tier=3,
        base_level=7,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=4500,
        bonus_rate_permyria=2000,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=78),
            Material(item_id='honor-leapstone-2', amount=2),
            Material(item_id='simple-oreha-fusion-material-1', amount=1),
            Material(item_id='honor-shard', amount=21),
            Material(item_id='silver', amount=6580),
            Material(item_id='gold', amount=35),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=125,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=250,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=750,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=5500,
        book_id='tailoring-basic-mending-3',
    ),
    HoningLevel(
        base_item_level=1335,
        next_item_level=1340,
        tier=3,
        base_level=8,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=3000,
        bonus_rate_permyria=2000,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=78),
            Material(item_id='honor-leapstone-2', amount=2),
            Material(item_id='simple-oreha-fusion-material-1', amount=1),
            Material(item_id='honor-shard', amount=21),
            Material(item_id='silver', amount=6740),
            Material(item_id='gold', amount=35),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=125,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=250,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=750,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=7000,
        book_id='tailoring-basic-mending-3',
    ),
    HoningLevel(
        base_item_level=1340,
        next_item_level=1345,
        tier=3,
        base_level=9,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=3000,
        bonus_rate_permyria=2000,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=96),
            Material(item_id='honor-leapstone-2', amount=3),
            Material(item_id='simple-oreha-fusion-material-1', amount=2),
            Material(item_id='honor-shard', amount=25),
            Material(item_id='silver', amount=6910),
            Material(item_id='gold', amount=35),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=84,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=167,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=500,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=3000,
        book_id='tailoring-basic-mending-3',
    ),
    HoningLevel(
        base_item_level=1345,
        next_item_level=1350,
        tier=3,
        base_level=10,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=3000,
        bonus_rate_permyria=2000,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=96),
            Material(item_id='honor-leapstone-2', amount=3),
            Material(item_id='simple-oreha-fusion-material-1', amount=2),
            Material(item_id='honor-shard', amount=25),
            Material(item_id='silver', amount=7070),
            Material(item_id='gold', amount=35),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=21,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=42,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=125,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=1500,
        book_id='tailoring-basic-mending-3',
    ),
    HoningLevel(
        base_item_level=1350,
        next_item_level=1355,
        tier=3,
        base_level=11,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=1500,
        bonus_rate_permyria=2000,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=96),
            Material(item_id='honor-leapstone-2', amount=3),
            Material(item_id='simple-oreha-fusion-material-1', amount=2),
            Material(item_id='honor-shard', amount=25),
            Material(item_id='silver', amount=7250),
            Material(item_id='gold', amount=35),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=21,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=42,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=125,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=1500,
        book_id='tailoring-basic-mending-3',
    ),
    HoningLevel(
        base_item_level=1355,
        next_item_level=1360,
        tier=3,
        base_level=12,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=1500,
        bonus_rate_permyria=2000,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=114),
            Material(item_id='honor-leapstone-2', amount=3),
            Material(item_id='simple-oreha-fusion-material-1', amount=2),
            Material(item_id='honor-shard', amount=30),
            Material(item_id='silver', amount=7430),
            Material(item_id='gold', amount=35),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=21,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=42,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=125,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=1500,
        book_id='tailoring-basic-mending-3',
    ),
    HoningLevel(
        base_item_level=1360,
        next_item_level=1365,
        tier=3,
        base_level=13,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=1500,
        bonus_rate_permyria=2000,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=114),
            Material(item_id='honor-leapstone-2', amount=4),
            Material(item_id='simple-oreha-fusion-material-1', amount=2),
            Material(item_id='honor-shard', amount=30),
            Material(item_id='silver', amount=7610),
            Material(item_id='gold', amount=35),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=21,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=42,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=125,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=1500,
        book_id='tailoring-basic-mending-3',
    ),
    HoningLevel(
        base_item_level=1365,
        next_item_level=1370,
        tier=3,
        base_level=14,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=1000,
        bonus_rate_permyria=2000,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=114),
            Material(item_id='honor-leapstone-2', amount=4),
            Material(item_id='simple-oreha-fusion-material-1', amount=2),
            Material(item_id='honor-shard', amount=30),
            Material(item_id='silver', amount=7800),
            Material(item_id='gold', amount=35),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=14,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=28,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=83,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=1000,
        book_id='tailoring-basic-mending-3',
    ),
    HoningLevel(
        base_item_level=1302,
        next_item_level=1304,
        tier=3,
        base_level=0,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=10000,
        bonus_rate_permyria=0,
        research_bonus_permyria=0,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=69),
            Material(item_id='honor-leapstone-2', amount=2),
            Material(item_id='honor-shard', amount=16),
            Material(item_id='silver', amount=7930),
        ),
    ),
    HoningLevel(
        base_item_level=1304,
        next_item_level=1307,
        tier=3,
        base_level=1,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=10000,
        bonus_rate_permyria=0,
        research_bonus_permyria=0,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=69),
            Material(item_id='honor-leapstone-2', amount=2),
            Material(item_id='honor-shard', amount=16),
            Material(item_id='silver', amount=8120),
        ),
    ),
    HoningLevel(
        base_item_level=1307,
        next_item_level=1310,
        tier=3,
        base_level=2,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=10000,
        bonus_rate_permyria=0,
        research_bonus_permyria=0,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=69),
            Material(item_id='honor-leapstone-2', amount=3),
            Material(item_id='honor-shard', amount=16),
            Material(item_id='silver', amount=8320),
        ),
    ),
    HoningLevel(
        base_item_level=1310,
        next_item_level=1315,
        tier=3,
        base_level=3,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=10000,
        bonus_rate_permyria=0,
        research_bonus_permyria=0,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=99),
            Material(item_id='honor-leapstone-2', amount=3),
            Material(item_id='simple-oreha-fusion-material-1', amount=1),
            Material(item_id='honor-shard', amount=23),
            Material(item_id='silver', amount=8520),
        ),
    ),
    HoningLevel(
        base_item_level=1315,
        next_item_level=1320,
        tier=3,
        base_level=4,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=10000,
        bonus_rate_permyria=0,
        research_bonus_permyria=0,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=99),
            Material(item_id='honor-leapstone-2', amount=3),
            Material(item_id='simple-oreha-fusion-material-1', amount=1),
            Material(item_id='honor-shard', amount=23),
            Material(item_id='silver', amount=8730),
        ),
    ),
    HoningLevel(
        base_item_level=1320,
        next_item_level=1325,
        tier=3,
        base_level=5,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=10000,
        bonus_rate_permyria=0,
        research_bonus_permyria=0,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=99),
            Material(item_id='honor-leapstone-2', amount=3),
            Material(item_id='simple-oreha-fusion-material-1', amount=1),
            Material(item_id='honor-shard', amount=23),
            Material(item_id='silver', amount=8950),
        ),
    ),
    HoningLevel(
        base_item_level=1325,
        next_item_level=1330,
        tier=3,
        base_level=6,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=6000,
        bonus_rate_permyria=2000,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=129),
            Material(item_id='honor-leapstone-2', amount=4),
            Material(item_id='simple-oreha-fusion-material-1', amount=2),
            Material(item_id='honor-shard', amount=30),
            Material(item_id='silver', amount=9390),
            Material(item_id='gold', amount=60),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=125,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=250,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=750,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=4000,
        book_id='metallurgy-basic-welding-3',
    ),
    HoningLevel(
        base_item_level=1330,
        next_item_level=1335,
        tier=3,
        base_level=7,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=4500,
        bonus_rate_permyria=2000,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=169),
            Material(item_id='honor-leapstone-2', amount=4),
            Material(item_id='simple-oreha-fusion-material-1', amount=2),
            Material(item_id='honor-shard', amount=30),
            Material(item_id='silver', amount=9390),
            Material(item_id='gold', amount=60),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=125,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=250,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=750,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=5500,
        book_id='metallurgy-basic-welding-3',
    ),
    HoningLevel(
        base_item_level=1335,
        next_item_level=1340,
        tier=3,
        base_level=8,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=3000,
        bonus_rate_permyria=2000,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=129),
            Material(item_id='honor-leapstone-2', amount=4),
            Material(item_id='simple-oreha-fusion-material-1', amount=2),
            Material(item_id='honor-shard', amount=30),
            Material(item_id='silver', amount=9620),
            Material(item_id='gold', amount=120),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=125,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=250,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=750,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=7000,
        book_id='metallurgy-basic-welding-3',
    ),
    HoningLevel(
        base_item_level=1340,
        next_item_level=1345,
        tier=3,
        base_level=9,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=3000,
        bonus_rate_permyria=2000,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=160),
            Material(item_id='honor-leapstone-2', amount=5),
            Material(item_id='simple-oreha-fusion-material-1', amount=2),
            Material(item_id='honor-shard', amount=37),
            Material(item_id='silver', amount=9860),
            Material(item_id='gold', amount=60),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=84,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=167,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=500,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=3000,
        book_id='metallurgy-basic-welding-3',
    ),
    HoningLevel(
        base_item_level=1345,
        next_item_level=1350,
        tier=3,
        base_level=10,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=3000,
        bonus_rate_permyria=2000,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=160),
            Material(item_id='honor-leapstone-2', amount=5),
            Material(item_id='simple-oreha-fusion-material-1', amount=2),
            Material(item_id='honor-shard', amount=37),
            Material(item_id='silver', amount=10100),
            Material(item_id='gold', amount=60),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=21,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=42,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=125,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=1500,
        book_id='metallurgy-basic-welding-3',
    ),
    HoningLevel(
        base_item_level=1350,
        next_item_level=1355,
        tier=3,
        base_level=11,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=1500,
        bonus_rate_permyria=2000,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=160),
            Material(item_id='honor-leapstone-2', amount=5),
            Material(item_id='simple-oreha-fusion-material-1', amount=2),
            Material(item_id='honor-shard', amount=37),
            Material(item_id='silver', amount=10350),
            Material(item_id='gold', amount=60),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=21,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=42,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=125,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=1500,
        book_id='metallurgy-basic-welding-3',
    ),
    HoningLevel(
        base_item_level=1355,
        next_item_level=1360,
        tier=3,
        base_level=12,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=1500,
        bonus_rate_permyria=2000,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=190),
            Material(item_id='honor-leapstone-2', amount=5),
            Material(item_id='simple-oreha-fusion-material-1', amount=3),
            Material(item_id='honor-shard', amount=44),
            Material(item_id='silver', amount=10600),
            Material(item_id='gold', amount=60),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=21,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=42,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=125,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=1500,
        book_id='metallurgy-basic-welding-3',
    ),
    HoningLevel(
        base_item_level=1360,
        next_item_level=1365,
        tier=3,
        base_level=13,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=1500,
        bonus_rate_permyria=2000,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=190),
            Material(item_id='honor-leapstone-2', amount=6),
            Material(item_id='simple-oreha-fusion-material-1', amount=3),
            Material(item_id='honor-shard', amount=44),
            Material(item_id='silver', amount=10860),
            Material(item_id='gold', amount=60),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=21,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=42,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=125,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=1500,
        book_id='metallurgy-basic-welding-3',
    ),
    HoningLevel(
        base_item_level=1365,
        next_item_level=1370,
        tier=3,
        base_level=14,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=1000,
        bonus_rate_permyria=2000,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=190),
            Material(item_id='honor-leapstone-2', amount=6),
            Material(item_id='simple-oreha-fusion-material-1', amount=3),
            Material(item_id='honor-shard', amount=44),
            Material(item_id='silver', amount=11130),
            Material(item_id='gold', amount=60),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=14,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=28,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=83,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=1000,
        book_id='metallurgy-basic-welding-3',
    ),
    # ----- Mid T3 (1370-1490) -----
    HoningLevel(
        base_item_level=1370,
        next_item_level=1375,
        tier=3,
        base_level=6,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=6000,
        bonus_rate_permyria=0,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=404),
            Material(item_id='great-honor-leapstone-2', amount=8),
            Material(item_id='basic-oreha-fusion-material-2', amount=6),
            Material(item_id='honor-shard', amount=108),
            Material(item_id='silver', amount=22380),
            Material(item_id='gold', amount=170),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=167,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=333,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=1000,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=4000,
        book_id='tailoring-applied-mending-4',
    ),
    HoningLevel(
        base_item_level=1375,
        next_item_level=1380,
        tier=3,
        base_level=7,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=4500,
        bonus_rate_permyria=0,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=404),
            Material(item_id='great-honor-leapstone-2', amount=10),
            Material(item_id='basic-oreha-fusion-material-2', amount=6),
            Material(item_id='honor-shard', amount=108),
            Material(item_id='silver', amount=22920),
            Material(item_id='gold', amount=170),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=125,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=250,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=750,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=4500,
        book_id='tailoring-applied-mending-4',
    ),
    HoningLevel(
        base_item_level=1380,
        next_item_level=1385,
        tier=3,
        base_level=8,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=3000,
        bonus_rate_permyria=0,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=404),
            Material(item_id='great-honor-leapstone-2', amount=10),
            Material(item_id='basic-oreha-fusion-material-2', amount=6),
            Material(item_id='honor-shard', amount=108),
            Material(item_id='silver', amount=23480),
            Material(item_id='gold', amount=170),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=84,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=167,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=500,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=3000,
        book_id='tailoring-applied-mending-4',
    ),
    HoningLevel(
        base_item_level=1385,
        next_item_level=1390,
        tier=3,
        base_level=9,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=3000,
        bonus_rate_permyria=0,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=498),
            Material(item_id='great-honor-leapstone-2', amount=10),
            Material(item_id='basic-oreha-fusion-material-2', amount=8),
            Material(item_id='honor-shard', amount=132),
            Material(item_id='silver', amount=24040),
            Material(item_id='gold', amount=170),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=84,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=167,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=500,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=3000,
        book_id='tailoring-applied-mending-4',
    ),
    HoningLevel(
        base_item_level=1390,
        next_item_level=1395,
        tier=3,
        base_level=10,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=3000,
        bonus_rate_permyria=0,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=498),
            Material(item_id='great-honor-leapstone-2', amount=10),
            Material(item_id='basic-oreha-fusion-material-2', amount=8),
            Material(item_id='honor-shard', amount=132),
            Material(item_id='silver', amount=24640),
            Material(item_id='gold', amount=170),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=84,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=167,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=500,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=3000,
        book_id='tailoring-applied-mending-4',
    ),
    HoningLevel(
        base_item_level=1395,
        next_item_level=1400,
        tier=3,
        base_level=11,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=1500,
        bonus_rate_permyria=0,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=498),
            Material(item_id='great-honor-leapstone-2', amount=12),
            Material(item_id='basic-oreha-fusion-material-2', amount=8),
            Material(item_id='honor-shard', amount=132),
            Material(item_id='silver', amount=25240),
            Material(item_id='gold', amount=170),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=21,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=42,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=125,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=750,
        book_id='tailoring-applied-mending-4',
    ),
    HoningLevel(
        base_item_level=1400,
        next_item_level=1405,
        tier=3,
        base_level=12,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=1500,
        bonus_rate_permyria=0,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=592),
            Material(item_id='great-honor-leapstone-2', amount=12),
            Material(item_id='basic-oreha-fusion-material-2', amount=8),
            Material(item_id='honor-shard', amount=158),
            Material(item_id='silver', amount=25860),
            Material(item_id='gold', amount=170),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=21,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=42,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=125,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=750,
        book_id='tailoring-applied-mending-4',
    ),
    HoningLevel(
        base_item_level=1405,
        next_item_level=1410,
        tier=3,
        base_level=13,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=1500,
        bonus_rate_permyria=0,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=592),
            Material(item_id='great-honor-leapstone-2', amount=12),
            Material(item_id='basic-oreha-fusion-material-2', amount=8),
            Material(item_id='honor-shard', amount=158),
            Material(item_id='silver', amount=26500),
            Material(item_id='gold', amount=170),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=21,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=42,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=125,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=750,
        book_id='tailoring-applied-mending-4',
    ),
    HoningLevel(
        base_item_level=1410,
        next_item_level=1415,
        tier=3,
        base_level=14,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=1000,
        bonus_rate_permyria=0,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=592),
            Material(item_id='great-honor-leapstone-2', amount=12),
            Material(item_id='basic-oreha-fusion-material-2', amount=8),
            Material(item_id='honor-shard', amount=158),
            Material(item_id='silver', amount=27160),
            Material(item_id='gold', amount=180),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=14,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=28,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=83,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=500,
        book_id='tailoring-applied-mending-4',
    ),
    HoningLevel(
        base_item_level=1415,
        next_item_level=1430,
        tier=3,
        base_level=15,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=1000,
        bonus_rate_permyria=0,
        research_bonus_permyria=0,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=686),
            Material(item_id='great-honor-leapstone-2', amount=14),
            Material(item_id='basic-oreha-fusion-material-2', amount=10),
            Material(item_id='honor-shard', amount=216),
            Material(item_id='silver', amount=27820),
            Material(item_id='gold', amount=210),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=14,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=28,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=83,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=500,
    ),
    HoningLevel(
        base_item_level=1430,
        next_item_level=1445,
        tier=3,
        base_level=16,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=1000,
        bonus_rate_permyria=0,
        research_bonus_permyria=0,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=686),
            Material(item_id='great-honor-leapstone-2', amount=16),
            Material(item_id='basic-oreha-fusion-material-2', amount=10),
            Material(item_id='honor-shard', amount=292),
            Material(item_id='silver', amount=28420),
            Material(item_id='gold', amount=250),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=14,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=28,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=83,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=500,
    ),
    HoningLevel(
        base_item_level=1445,
        next_item_level=1460,
        tier=3,
        base_level=17,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=500,
        bonus_rate_permyria=0,
        research_bonus_permyria=0,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=686),
            Material(item_id='great-honor-leapstone-2', amount=16),
            Material(item_id='basic-oreha-fusion-material-2', amount=12),
            Material(item_id='honor-shard', amount=396),
            Material(item_id='silver', amount=29040),
            Material(item_id='gold', amount=280),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=5,
                        max_amount=36),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=9,
                        max_amount=18),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=28,
                        max_amount=6),
        ),
        max_enhancement_rate_permyria=500,
    ),
    HoningLevel(
        base_item_level=1460,
        next_item_level=1475,
        tier=3,
        base_level=18,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=500,
        bonus_rate_permyria=0,
        research_bonus_permyria=0,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=780),
            Material(item_id='great-honor-leapstone-2', amount=18),
            Material(item_id='basic-oreha-fusion-material-2', amount=14),
            Material(item_id='honor-shard', amount=536),
            Material(item_id='silver', amount=29660),
            Material(item_id='gold', amount=320),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=5,
                        max_amount=36),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=9,
                        max_amount=18),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=28,
                        max_amount=6),
        ),
        max_enhancement_rate_permyria=500,
    ),
    HoningLevel(
        base_item_level=1475,
        next_item_level=1490,
        tier=3,
        base_level=19,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=300,
        bonus_rate_permyria=0,
        research_bonus_permyria=0,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=780),
            Material(item_id='great-honor-leapstone-2', amount=20),
            Material(item_id='basic-oreha-fusion-material-2', amount=14),
            Material(item_id='honor-shard', amount=728),
            Material(item_id='silver', amount=30320),
            Material(item_id='gold', amount=350),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=3,
                        max_amount=36),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=6,
                        max_amount=18),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=17,
                        max_amount=6),
        ),
        max_enhancement_rate_permyria=300,
    ),
    HoningLevel(
        base_item_level=1370,
        next_item_level=1375,
        tier=3,
        base_level=6,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=6000,
        bonus_rate_permyria=0,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=672),
            Material(item_id='great-honor-leapstone-2', amount=12),
            Material(item_id='basic-oreha-fusion-material-2', amount=6),
            Material(item_id='honor-shard', amount=156),
            Material(item_id='silver', amount=31920),
            Material(item_id='gold', amount=320),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=167,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=333,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=1000,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=4000,
        book_id='metallurgy-applied-welding-4',
    ),
    HoningLevel(
        base_item_level=1375,
        next_item_level=1380,
        tier=3,
        base_level=7,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=4500,
        bonus_rate_permyria=0,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=672),
            Material(item_id='great-honor-leapstone-2', amount=14),
            Material(item_id='basic-oreha-fusion-material-2', amount=6),
            Material(item_id='honor-shard', amount=156),
            Material(item_id='silver', amount=32700),
            Material(item_id='gold', amount=320),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=125,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=250,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=750,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=4500,
        book_id='metallurgy-applied-welding-4',
    ),
    HoningLevel(
        base_item_level=1380,
        next_item_level=1385,
        tier=3,
        base_level=8,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=3000,
        bonus_rate_permyria=0,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=672),
            Material(item_id='great-honor-leapstone-2', amount=14),
            Material(item_id='basic-oreha-fusion-material-2', amount=8),
            Material(item_id='honor-shard', amount=156),
            Material(item_id='silver', amount=33520),
            Material(item_id='gold', amount=320),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=84,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=167,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=500,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=3000,
        book_id='metallurgy-applied-welding-4',
    ),
    HoningLevel(
        base_item_level=1385,
        next_item_level=1390,
        tier=3,
        base_level=9,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=3000,
        bonus_rate_permyria=0,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=830),
            Material(item_id='great-honor-leapstone-2', amount=16),
            Material(item_id='basic-oreha-fusion-material-2', amount=8),
            Material(item_id='honor-shard', amount=192),
            Material(item_id='silver', amount=34340),
            Material(item_id='gold', amount=320),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=84,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=167,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=500,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=3000,
        book_id='metallurgy-applied-welding-4',
    ),
    HoningLevel(
        base_item_level=1390,
        next_item_level=1395,
        tier=3,
        base_level=10,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=3000,
        bonus_rate_permyria=0,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=830),
            Material(item_id='great-honor-leapstone-2', amount=16),
            Material(item_id='basic-oreha-fusion-material-2', amount=8),
            Material(item_id='honor-shard', amount=192),
            Material(item_id='silver', amount=35180),
            Material(item_id='gold', amount=330),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=84,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=167,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=500,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=3000,
        book_id='metallurgy-applied-welding-4',
    ),
    HoningLevel(
        base_item_level=1395,
        next_item_level=1400,
        tier=3,
        base_level=11,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=1500,
        bonus_rate_permyria=0,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=830),
            Material(item_id='great-honor-leapstone-2', amount=18),
            Material(item_id='basic-oreha-fusion-material-2', amount=8),
            Material(item_id='honor-shard', amount=192),
            Material(item_id='silver', amount=36040),
            Material(item_id='gold', amount=330),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=21,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=42,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=125,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=750,
        book_id='metallurgy-applied-welding-4',
    ),
    HoningLevel(
        base_item_level=1400,
        next_item_level=1405,
        tier=3,
        base_level=12,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=1500,
        bonus_rate_permyria=0,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=986),
            Material(item_id='great-honor-leapstone-2', amount=18),
            Material(item_id='basic-oreha-fusion-material-2', amount=10),
            Material(item_id='honor-shard', amount=228),
            Material(item_id='silver', amount=36940),
            Material(item_id='gold', amount=330),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=21,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=42,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=125,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=750,
        book_id='metallurgy-applied-welding-4',
    ),
    HoningLevel(
        base_item_level=1405,
        next_item_level=1410,
        tier=3,
        base_level=13,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=1500,
        bonus_rate_permyria=0,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=968),
            Material(item_id='great-honor-leapstone-2', amount=20),
            Material(item_id='basic-oreha-fusion-material-2', amount=10),
            Material(item_id='honor-shard', amount=228),
            Material(item_id='silver', amount=37840),
            Material(item_id='gold', amount=330),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=21,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=42,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=125,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=750,
        book_id='metallurgy-applied-welding-4',
    ),
    HoningLevel(
        base_item_level=1410,
        next_item_level=1415,
        tier=3,
        base_level=14,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=1000,
        bonus_rate_permyria=0,
        research_bonus_permyria=1000,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=986),
            Material(item_id='great-honor-leapstone-2', amount=20),
            Material(item_id='basic-oreha-fusion-material-2', amount=10),
            Material(item_id='honor-shard', amount=228),
            Material(item_id='silver', amount=38760),
            Material(item_id='gold', amount=330),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=14,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=28,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=83,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=500,
        book_id='metallurgy-applied-welding-4',
    ),
    HoningLevel(
        base_item_level=1415,
        next_item_level=1430,
        tier=3,
        base_level=15,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=1000,
        bonus_rate_permyria=0,
        research_bonus_permyria=0,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=1144),
            Material(item_id='great-honor-leapstone-2', amount=22),
            Material(item_id='basic-oreha-fusion-material-2', amount=12),
            Material(item_id='honor-shard', amount=310),
            Material(item_id='silver', amount=39720),
            Material(item_id='gold', amount=410),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=14,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=28,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=83,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=500,
    ),
    HoningLevel(
        base_item_level=1430,
        next_item_level=1445,
        tier=3,
        base_level=16,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=1000,
        bonus_rate_permyria=0,
        research_bonus_permyria=0,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=1144),
            Material(item_id='great-honor-leapstone-2', amount=24),
            Material(item_id='basic-oreha-fusion-material-2', amount=14),
            Material(item_id='honor-shard', amount=422),
            Material(item_id='silver', amount=40580),
            Material(item_id='gold', amount=480),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=14,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=28,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=83,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=500,
    ),
    HoningLevel(
        base_item_level=1445,
        next_item_level=1460,
        tier=3,
        base_level=17,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=500,
        bonus_rate_permyria=0,
        research_bonus_permyria=0,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=1144),
            Material(item_id='great-honor-leapstone-2', amount=28),
            Material(item_id='basic-oreha-fusion-material-2', amount=16),
            Material(item_id='honor-shard', amount=572),
            Material(item_id='silver', amount=41460),
            Material(item_id='gold', amount=540),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=5,
                        max_amount=36),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=9,
                        max_amount=18),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=28,
                        max_amount=6),
        ),
        max_enhancement_rate_permyria=500,
    ),
    HoningLevel(
        base_item_level=1460,
        next_item_level=1475,
        tier=3,
        base_level=18,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=500,
        bonus_rate_permyria=0,
        research_bonus_permyria=0,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=1300),
            Material(item_id='great-honor-leapstone-2', amount=30),
            Material(item_id='basic-oreha-fusion-material-2', amount=18),
            Material(item_id='honor-shard', amount=776),
            Material(item_id='silver', amount=42360),
            Material(item_id='gold', amount=640),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=5,
                        max_amount=36),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=9,
                        max_amount=18),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=28,
                        max_amount=6),
        ),
        max_enhancement_rate_permyria=500,
    ),
    HoningLevel(
        base_item_level=1475,
        next_item_level=1490,
        tier=3,
        base_level=19,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=300,
        bonus_rate_permyria=0,
        research_bonus_permyria=0,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=1300),
            Material(item_id='great-honor-leapstone-2', amount=32),
            Material(item_id='basic-oreha-fusion-material-2', amount=20),
            Material(item_id='honor-shard', amount=1054),
            Material(item_id='silver', amount=43260),
            Material(item_id='gold', amount=730),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=3,
                        max_amount=36),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=6,
                        max_amount=18),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=17,
                        max_amount=6),
        ),
        max_enhancement_rate_permyria=300,
    ),
    # ----- High T3 (1490-1575) -----
    HoningLevel(
        base_item_level=1490,
        next_item_level=1505,
        tier=3,
        base_level=20,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=300,
        bonus_rate_permyria=0,
        research_bonus_permyria=0,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=780),
            Material(item_id='great-honor-leapstone-2', amount=22),
            Material(item_id='basic-oreha-fusion-material-2', amount=16),
            Material(item_id='honor-shard', amount=988),
            Material(item_id='silver', amount=30980),
            Material(item_id='gold', amount=360),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=3,
                        max_amount=36),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=6,
                        max_amount=18),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=17,
                        max_amount=6),
        ),
        max_enhancement_rate_permyria=300,
    ),
    HoningLevel(
        base_item_level=1505,
        next_item_level=1520,
        tier=3,
        base_level=21,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=100,
        bonus_rate_permyria=0,
        research_bonus_permyria=0,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=874),
            Material(item_id='great-honor-leapstone-2', amount=24),
            Material(item_id='basic-oreha-fusion-material-2', amount=18),
            Material(item_id='honor-shard', amount=1340),
            Material(item_id='silver', amount=31640),
            Material(item_id='gold', amount=380),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=1,
                        max_amount=48),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=2,
                        max_amount=24),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=4,
                        max_amount=8),
        ),
        max_enhancement_rate_permyria=100,
    ),
    HoningLevel(
        base_item_level=1520,
        next_item_level=1535,
        tier=3,
        base_level=22,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=100,
        bonus_rate_permyria=0,
        research_bonus_permyria=0,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=874),
            Material(item_id='great-honor-leapstone-2', amount=26),
            Material(item_id='basic-oreha-fusion-material-2', amount=20),
            Material(item_id='honor-shard', amount=1818),
            Material(item_id='silver', amount=32320),
            Material(item_id='gold', amount=390),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=1,
                        max_amount=48),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=2,
                        max_amount=24),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=4,
                        max_amount=8),
        ),
        max_enhancement_rate_permyria=100,
    ),
    HoningLevel(
        base_item_level=1535,
        next_item_level=1550,
        tier=3,
        base_level=23,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=50,
        bonus_rate_permyria=0,
        research_bonus_permyria=0,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=874),
            Material(item_id='great-honor-leapstone-2', amount=28),
            Material(item_id='basic-oreha-fusion-material-2', amount=22),
            Material(item_id='honor-shard', amount=2466),
            Material(item_id='silver', amount=33040),
            Material(item_id='gold', amount=400),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=1,
                        max_amount=48),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=2,
                        max_amount=24),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=4,
                        max_amount=8),
        ),
        max_enhancement_rate_permyria=100,
    ),
    HoningLevel(
        base_item_level=1550,
        next_item_level=1575,
        tier=3,
        base_level=24,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=50,
        bonus_rate_permyria=0,
        research_bonus_permyria=0,
        cost=(
            Material(item_id='crystallized-guardian-stone-0', amount=968),
            Material(item_id='great-honor-leapstone-2', amount=30),
            Material(item_id='basic-oreha-fusion-material-2', amount=24),
            Material(item_id='honor-shard', amount=3346),
            Material(item_id='silver', amount=33740),
            Material(item_id='gold', amount=420),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=1,
                        max_amount=48),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=2,
                        max_amount=24),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=4,
                        max_amount=8),
        ),
        max_enhancement_rate_permyria=100,
    ),
    HoningLevel(
        base_item_level=1490,
        next_item_level=1505,
        tier=3,
        base_level=20,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=300,
        bonus_rate_permyria=0,
        research_bonus_permyria=0,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=1300),
            Material(item_id='great-honor-leapstone-2', amount=34),
            Material(item_id='basic-oreha-fusion-material-2', amount=22),
            Material(item_id='honor-shard', amount=1432),
            Material(item_id='silver', amount=44200),
            Material(item_id='gold', amount=750),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=3,
                        max_amount=36),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=6,
                        max_amount=18),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=17,
                        max_amount=6),
        ),
        max_enhancement_rate_permyria=300,
    ),
    HoningLevel(
        base_item_level=1505,
        next_item_level=1520,
        tier=3,
        base_level=21,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=100,
        bonus_rate_permyria=0,
        research_bonus_permyria=0,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=1458),
            Material(item_id='great-honor-leapstone-2', amount=38),
            Material(item_id='basic-oreha-fusion-material-2', amount=26),
            Material(item_id='honor-shard', amount=1944),
            Material(item_id='silver', amount=45160),
            Material(item_id='gold', amount=780),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=1,
                        max_amount=48),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=2,
                        max_amount=24),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=4,
                        max_amount=8),
        ),
        max_enhancement_rate_permyria=100,
    ),
    HoningLevel(
        base_item_level=1520,
        next_item_level=1535,
        tier=3,
        base_level=22,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=100,
        bonus_rate_permyria=0,
        research_bonus_permyria=0,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=1458),
            Material(item_id='great-honor-leapstone-2', amount=42),
            Material(item_id='basic-oreha-fusion-material-2', amount=28),
            Material(item_id='honor-shard', amount=2640),
            Material(item_id='silver', amount=46140),
            Material(item_id='gold', amount=810),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=1,
                        max_amount=48),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=2,
                        max_amount=24),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=4,
                        max_amount=8),
        ),
        max_enhancement_rate_permyria=100,
    ),
    HoningLevel(
        base_item_level=1535,
        next_item_level=1550,
        tier=3,
        base_level=23,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=50,
        bonus_rate_permyria=0,
        research_bonus_permyria=0,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=1458),
            Material(item_id='great-honor-leapstone-2', amount=44),
            Material(item_id='basic-oreha-fusion-material-2', amount=32),
            Material(item_id='honor-shard', amount=3586),
            Material(item_id='silver', amount=47160),
            Material(item_id='gold', amount=840),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=1,
                        max_amount=48),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=2,
                        max_amount=24),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=4,
                        max_amount=8),
        ),
        max_enhancement_rate_permyria=100,
    ),
    HoningLevel(
        base_item_level=1550,
        next_item_level=1575,
        tier=3,
        base_level=24,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=50,
        bonus_rate_permyria=0,
        research_bonus_permyria=0,
        cost=(
            Material(item_id='crystallized-destruction-stone-0', amount=1614),
            Material(item_id='great-honor-leapstone-2', amount=48),
            Material(item_id='basic-oreha-fusion-material-2', amount=36),
            Material(item_id='honor-shard', amount=4868),
            Material(item_id='silver', amount=48180),
            Material(item_id='gold', amount=870),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=1,
                        max_amount=48),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=2,
                        max_amount=24),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=4,
                        max_amount=8),
        ),
        max_enhancement_rate_permyria=100,
    ),
)

HONES_DICT = {(h.base_item_level, h.equipment_type): h for h in HONES}
