from dataclasses import dataclass
import enum
from typing import Optional, Tuple


class EquipmentType(enum.Enum):
    ARMOR = 0
    WEAPON = 1


@dataclass(frozen=True)
class Material:
    item_id: str
    amount: int


@dataclass(frozen=True)
class Enhancement:
    item_id: str
    rate_increase_permyria: int
    max_amount: int


@dataclass(frozen=True)
class HoningLevel:
    base_item_level: int
    next_item_level: int
    tier: int
    base_level: int
    equipment_type: EquipmentType
    base_rate_permyria: int
    cost: Tuple[Material]
    enhancements: Tuple[Enhancement] = ()
    max_enhancement_rate_permyria: int = 0
    book_id: Optional[str] = None


HONES = (
    # ----- Low T3 (1302-1370) -----
    HoningLevel(
        base_item_level=1302,
        next_item_level=1304,
        tier=3,
        base_level=0,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=10000,
        cost=(
            Material(item_id='guardian-stone-crystal-0', amount=82),
            Material(item_id='honor-shard', amount=22),
            Material(item_id='honor-leapstone-2', amount=2),
            Material(item_id='silver', amount=11100),
        ),
    ),
    HoningLevel(
        base_item_level=1304,
        next_item_level=1307,
        tier=3,
        base_level=1,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=10000,
        cost=(
            Material(item_id='guardian-stone-crystal-0', amount=82),
            Material(item_id='honor-shard', amount=22),
            Material(item_id='honor-leapstone-2', amount=2),
            Material(item_id='silver', amount=11380),
        ),
    ),
    HoningLevel(
        base_item_level=1307,
        next_item_level=1310,
        tier=3,
        base_level=2,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=10000,
        cost=(
            Material(item_id='guardian-stone-crystal-0', amount=82),
            Material(item_id='honor-shard', amount=22),
            Material(item_id='honor-leapstone-2', amount=2),
            Material(item_id='silver', amount=11660),
        ),
    ),
    HoningLevel(
        base_item_level=1310,
        next_item_level=1315,
        tier=3,
        base_level=3,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=10000,
        cost=(
            Material(item_id='guardian-stone-crystal-0', amount=120),
            Material(item_id='honor-shard', amount=32),
            Material(item_id='honor-leapstone-2', amount=4),
            Material(item_id='simple-oreha-fusion-material-1', amount=2),
            Material(item_id='silver', amount=11960),
        ),
    ),
    HoningLevel(
        base_item_level=1315,
        next_item_level=1320,
        tier=3,
        base_level=4,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=10000,
        cost=(
            Material(item_id='guardian-stone-crystal-0', amount=120),
            Material(item_id='honor-shard', amount=32),
            Material(item_id='honor-leapstone-2', amount=4),
            Material(item_id='simple-oreha-fusion-material-1', amount=2),
            Material(item_id='silver', amount=12840),
        ),
    ),
    HoningLevel(
        base_item_level=1320,
        next_item_level=1325,
        tier=3,
        base_level=5,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=10000,
        cost=(
            Material(item_id='guardian-stone-crystal-0', amount=120),
            Material(item_id='honor-shard', amount=32),
            Material(item_id='honor-leapstone-2', amount=4),
            Material(item_id='simple-oreha-fusion-material-1', amount=2),
            Material(item_id='silver', amount=12540),
        ),
    ),
    HoningLevel(
        base_item_level=1325,
        next_item_level=1330,
        tier=3,
        base_level=6,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=6000,
        cost=(
            Material(item_id='guardian-stone-crystal-0', amount=156),
            Material(item_id='honor-shard', amount=42),
            Material(item_id='honor-leapstone-2', amount=4),
            Material(item_id='simple-oreha-fusion-material-1', amount=2),
            Material(item_id='silver', amount=12840),
            Material(item_id='gold', amount=70),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=125,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=250,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=750,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=4000,
        book_id='tailoring-basic-mending-3',
    ),
    HoningLevel(
        base_item_level=1330,
        next_item_level=1335,
        tier=3,
        base_level=7,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=4500,
        cost=(
            Material(item_id='guardian-stone-crystal-0', amount=156),
            Material(item_id='honor-shard', amount=42),
            Material(item_id='honor-leapstone-2', amount=4),
            Material(item_id='simple-oreha-fusion-material-1', amount=2),
            Material(item_id='silver', amount=13160),
            Material(item_id='gold', amount=70),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=125,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=250,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=750,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=5500,
        book_id='tailoring-basic-mending-3',
    ),
    HoningLevel(
        base_item_level=1335,
        next_item_level=1340,
        tier=3,
        base_level=8,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=3000,
        cost=(
            Material(item_id='guardian-stone-crystal-0', amount=156),
            Material(item_id='honor-shard', amount=42),
            Material(item_id='honor-leapstone-2', amount=4),
            Material(item_id='simple-oreha-fusion-material-1', amount=2),
            Material(item_id='silver', amount=13480),
            Material(item_id='gold', amount=70),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=125,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=250,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=750,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=7000,
        book_id='tailoring-basic-mending-3',
    ),
    HoningLevel(
        base_item_level=1340,
        next_item_level=1345,
        tier=3,
        base_level=9,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=3000,
        cost=(
            Material(item_id='guardian-stone-crystal-0', amount=192),
            Material(item_id='honor-shard', amount=50),
            Material(item_id='honor-leapstone-2', amount=6),
            Material(item_id='simple-oreha-fusion-material-1', amount=4),
            Material(item_id='silver', amount=13820),
            Material(item_id='gold', amount=70),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=84,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=167,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=500,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=3000,
        book_id='tailoring-basic-mending-3',
    ),
    HoningLevel(
        base_item_level=1345,
        next_item_level=1350,
        tier=3,
        base_level=10,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=3000,
        cost=(
            Material(item_id='guardian-stone-crystal-0', amount=192),
            Material(item_id='honor-shard', amount=50),
            Material(item_id='honor-leapstone-2', amount=6),
            Material(item_id='simple-oreha-fusion-material-1', amount=4),
            Material(item_id='silver', amount=14140),
            Material(item_id='gold', amount=70),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=21,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=42,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=125,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=1500,
        book_id='tailoring-basic-mending-3',
    ),
    HoningLevel(
        base_item_level=1350,
        next_item_level=1355,
        tier=3,
        base_level=11,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=1500,
        cost=(
            Material(item_id='guardian-stone-crystal-0', amount=192),
            Material(item_id='honor-shard', amount=50),
            Material(item_id='honor-leapstone-2', amount=6),
            Material(item_id='simple-oreha-fusion-material-1', amount=4),
            Material(item_id='silver', amount=14500),
            Material(item_id='gold', amount=70),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=21,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=42,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=125,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=1500,
        book_id='tailoring-basic-mending-3',
    ),
    HoningLevel(
        base_item_level=1355,
        next_item_level=1360,
        tier=3,
        base_level=12,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=1500,
        cost=(
            Material(item_id='guardian-stone-crystal-0', amount=228),
            Material(item_id='honor-shard', amount=60),
            Material(item_id='honor-leapstone-2', amount=6),
            Material(item_id='simple-oreha-fusion-material-1', amount=4),
            Material(item_id='silver', amount=14860),
            Material(item_id='gold', amount=70),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=21,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=42,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=125,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=1500,
        book_id='tailoring-basic-mending-3',
    ),
    HoningLevel(
        base_item_level=1360,
        next_item_level=1365,
        tier=3,
        base_level=13,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=1500,
        cost=(
            Material(item_id='guardian-stone-crystal-0', amount=228),
            Material(item_id='honor-shard', amount=60),
            Material(item_id='honor-leapstone-2', amount=8),
            Material(item_id='simple-oreha-fusion-material-1', amount=4),
            Material(item_id='silver', amount=15220),
            Material(item_id='gold', amount=70),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=21,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=42,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=125,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=1500,
        book_id='tailoring-basic-mending-3',
    ),
    HoningLevel(
        base_item_level=1365,
        next_item_level=1370,
        tier=3,
        base_level=14,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=1000,
        cost=(
            Material(item_id='guardian-stone-crystal-0', amount=228),
            Material(item_id='honor-shard', amount=60),
            Material(item_id='honor-leapstone-2', amount=8),
            Material(item_id='simple-oreha-fusion-material-1', amount=4),
            Material(item_id='silver', amount=15600),
            Material(item_id='gold', amount=70),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=14,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=28,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=83,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=1000,
        book_id='tailoring-basic-mending-3',
    ),
    HoningLevel(
        base_item_level=1302,
        next_item_level=1304,
        tier=3,
        base_level=0,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=10000,
        cost=(
            Material(item_id='destruction-stone-crystal-0', amount=138),
            Material(item_id='honor-shard', amount=32),
            Material(item_id='honor-leapstone-2', amount=4),
            Material(item_id='silver', amount=15860),
        ),
    ),
    HoningLevel(
        base_item_level=1304,
        next_item_level=1307,
        tier=3,
        base_level=1,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=10000,
        cost=(
            Material(item_id='destruction-stone-crystal-0', amount=138),
            Material(item_id='honor-shard', amount=32),
            Material(item_id='honor-leapstone-2', amount=4),
            Material(item_id='silver', amount=16240),
        ),
    ),
    HoningLevel(
        base_item_level=1307,
        next_item_level=1310,
        tier=3,
        base_level=2,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=10000,
        cost=(
            Material(item_id='destruction-stone-crystal-0', amount=198),
            Material(item_id='honor-shard', amount=32),
            Material(item_id='honor-leapstone-2', amount=6),
            Material(item_id='silver', amount=16640),
        ),
    ),
    HoningLevel(
        base_item_level=1310,
        next_item_level=1315,
        tier=3,
        base_level=3,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=10000,
        cost=(
            Material(item_id='destruction-stone-crystal-0', amount=198),
            Material(item_id='honor-shard', amount=46),
            Material(item_id='honor-leapstone-2', amount=6),
            Material(item_id='simple-oreha-fusion-material-1', amount=2),
            Material(item_id='silver', amount=17040),
        ),
    ),
    HoningLevel(
        base_item_level=1315,
        next_item_level=1320,
        tier=3,
        base_level=4,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=10000,
        cost=(
            Material(item_id='destruction-stone-crystal-0', amount=198),
            Material(item_id='honor-shard', amount=46),
            Material(item_id='honor-leapstone-2', amount=6),
            Material(item_id='simple-oreha-fusion-material-1', amount=2),
            Material(item_id='silver', amount=17060),
        ),
    ),
    HoningLevel(
        base_item_level=1320,
        next_item_level=1325,
        tier=3,
        base_level=5,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=10000,
        cost=(
            Material(item_id='destruction-stone-crystal-0', amount=198),
            Material(item_id='honor-shard', amount=46),
            Material(item_id='honor-leapstone-2', amount=6),
            Material(item_id='simple-oreha-fusion-material-1', amount=2),
            Material(item_id='silver', amount=17900),
        ),
    ),
    HoningLevel(
        base_item_level=1325,
        next_item_level=1330,
        tier=3,
        base_level=6,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=6000,
        cost=(
            Material(item_id='destruction-stone-crystal-0', amount=258),
            Material(item_id='honor-shard', amount=60),
            Material(item_id='honor-leapstone-2', amount=8),
            Material(item_id='simple-oreha-fusion-material-1', amount=4),
            Material(item_id='silver', amount=18320),
            Material(item_id='gold', amount=120),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=125,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=250,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=750,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=4000,
        book_id='tailoring-basic-mending-3',
    ),
    HoningLevel(
        base_item_level=1330,
        next_item_level=1335,
        tier=3,
        base_level=7,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=4500,
        cost=(
            Material(item_id='destruction-stone-crystal-0', amount=258),
            Material(item_id='honor-shard', amount=60),
            Material(item_id='honor-leapstone-2', amount=8),
            Material(item_id='simple-oreha-fusion-material-1', amount=4),
            Material(item_id='silver', amount=18780),
            Material(item_id='gold', amount=120),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=125,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=250,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=750,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=5500,
        book_id='tailoring-basic-mending-3',
    ),
    HoningLevel(
        base_item_level=1335,
        next_item_level=1340,
        tier=3,
        base_level=8,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=3000,
        cost=(
            Material(item_id='destruction-stone-crystal-0', amount=258),
            Material(item_id='honor-shard', amount=60),
            Material(item_id='honor-leapstone-2', amount=8),
            Material(item_id='simple-oreha-fusion-material-1', amount=4),
            Material(item_id='silver', amount=19240),
            Material(item_id='gold', amount=120),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=125,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=250,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=750,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=7000,
        book_id='tailoring-basic-mending-3',
    ),
    HoningLevel(
        base_item_level=1340,
        next_item_level=1345,
        tier=3,
        base_level=9,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=3000,
        cost=(
            Material(item_id='destruction-stone-crystal-0', amount=320),
            Material(item_id='honor-shard', amount=74),
            Material(item_id='honor-leapstone-2', amount=10),
            Material(item_id='simple-oreha-fusion-material-1', amount=4),
            Material(item_id='silver', amount=19720),
            Material(item_id='gold', amount=120),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=84,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=167,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=500,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=3000,
        book_id='tailoring-basic-mending-3',
    ),
    HoningLevel(
        base_item_level=1345,
        next_item_level=1350,
        tier=3,
        base_level=10,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=3000,
        cost=(
            Material(item_id='destruction-stone-crystal-0', amount=320),
            Material(item_id='honor-shard', amount=74),
            Material(item_id='honor-leapstone-2', amount=10),
            Material(item_id='simple-oreha-fusion-material-1', amount=4),
            Material(item_id='silver', amount=20200),
            Material(item_id='gold', amount=120),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=21,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=42,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=125,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=1500,
        book_id='tailoring-basic-mending-3',
    ),
    HoningLevel(
        base_item_level=1350,
        next_item_level=1355,
        tier=3,
        base_level=11,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=1500,
        cost=(
            Material(item_id='destruction-stone-crystal-0', amount=320),
            Material(item_id='honor-shard', amount=74),
            Material(item_id='honor-leapstone-2', amount=10),
            Material(item_id='simple-oreha-fusion-material-1', amount=4),
            Material(item_id='silver', amount=20700),
            Material(item_id='gold', amount=120),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=21,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=42,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=125,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=1500,
        book_id='tailoring-basic-mending-3',
    ),
    HoningLevel(
        base_item_level=1355,
        next_item_level=1360,
        tier=3,
        base_level=12,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=1500,
        cost=(
            Material(item_id='destruction-stone-crystal-0', amount=380),
            Material(item_id='honor-shard', amount=88),
            Material(item_id='honor-leapstone-2', amount=12),
            Material(item_id='simple-oreha-fusion-material-1', amount=6),
            Material(item_id='silver', amount=21200),
            Material(item_id='gold', amount=120),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=21,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=42,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=125,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=1500,
        book_id='tailoring-basic-mending-3',
    ),
    HoningLevel(
        base_item_level=1360,
        next_item_level=1365,
        tier=3,
        base_level=13,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=1500,
        cost=(
            Material(item_id='destruction-stone-crystal-0', amount=380),
            Material(item_id='honor-shard', amount=88),
            Material(item_id='honor-leapstone-2', amount=12),
            Material(item_id='simple-oreha-fusion-material-1', amount=6),
            Material(item_id='silver', amount=21720),
            Material(item_id='gold', amount=120),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=21,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=42,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=125,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=1500,
        book_id='tailoring-basic-mending-3',
    ),
    HoningLevel(
        base_item_level=1365,
        next_item_level=1370,
        tier=3,
        base_level=14,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=1000,
        cost=(
            Material(item_id='destruction-stone-crystal-0', amount=380),
            Material(item_id='honor-shard', amount=88),
            Material(item_id='honor-leapstone-2', amount=12),
            Material(item_id='simple-oreha-fusion-material-1', amount=6),
            Material(item_id='silver', amount=22260),
            Material(item_id='gold', amount=120),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=14,
                        max_amount=24),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=28,
                        max_amount=12),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=83,
                        max_amount=4),
        ),
        max_enhancement_rate_permyria=1000,
        book_id='tailoring-basic-mending-3',
    ),
    # ----- Mid T3 (1370-1490) -----
    HoningLevel(
        base_item_level=1370,
        next_item_level=1375,
        tier=3,
        base_level=6,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=6000,
        cost=(
            Material(item_id='guardian-stone-crystal-0', amount=404),
            Material(item_id='honor-shard', amount=108),
            Material(item_id='great-honor-leapstone-2', amount=8),
            Material(item_id='basic-oreha-fusion-material-2', amount=6),
            Material(item_id='silver', amount=22380),
            Material(item_id='gold', amount=170),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=167,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=333,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=1000,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=4000,
        book_id='tailoring-applied-mending-4',
    ),
    HoningLevel(
        base_item_level=1375,
        next_item_level=1380,
        tier=3,
        base_level=7,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=4500,
        cost=(
            Material(item_id='guardian-stone-crystal-0', amount=404),
            Material(item_id='honor-shard', amount=108),
            Material(item_id='great-honor-leapstone-2', amount=10),
            Material(item_id='basic-oreha-fusion-material-2', amount=6),
            Material(item_id='silver', amount=22920),
            Material(item_id='gold', amount=170),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=125,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=250,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=750,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=4500,
        book_id='tailoring-applied-mending-4',
    ),
    HoningLevel(
        base_item_level=1380,
        next_item_level=1385,
        tier=3,
        base_level=8,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=3000,
        cost=(
            Material(item_id='guardian-stone-crystal-0', amount=404),
            Material(item_id='honor-shard', amount=108),
            Material(item_id='great-honor-leapstone-2', amount=10),
            Material(item_id='basic-oreha-fusion-material-2', amount=6),
            Material(item_id='silver', amount=23480),
            Material(item_id='gold', amount=170),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=84,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=167,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=500,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=3000,
        book_id='tailoring-applied-mending-4',
    ),
    HoningLevel(
        base_item_level=1385,
        next_item_level=1390,
        tier=3,
        base_level=9,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=3000,
        cost=(
            Material(item_id='guardian-stone-crystal-0', amount=498),
            Material(item_id='honor-shard', amount=132),
            Material(item_id='great-honor-leapstone-2', amount=10),
            Material(item_id='basic-oreha-fusion-material-2', amount=8),
            Material(item_id='silver', amount=24040),
            Material(item_id='gold', amount=170),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=84,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=167,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=500,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=3000,
        book_id='tailoring-applied-mending-4',
    ),
    HoningLevel(
        base_item_level=1390,
        next_item_level=1395,
        tier=3,
        base_level=10,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=3000,
        cost=(
            Material(item_id='guardian-stone-crystal-0', amount=498),
            Material(item_id='honor-shard', amount=132),
            Material(item_id='great-honor-leapstone-2', amount=10),
            Material(item_id='basic-oreha-fusion-material-2', amount=8),
            Material(item_id='silver', amount=24640),
            Material(item_id='gold', amount=170),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=84,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=167,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=500,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=3000,
        book_id='tailoring-applied-mending-4',
    ),
    HoningLevel(
        base_item_level=1395,
        next_item_level=1400,
        tier=3,
        base_level=11,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=1500,
        cost=(
            Material(item_id='guardian-stone-crystal-0', amount=498),
            Material(item_id='honor-shard', amount=132),
            Material(item_id='great-honor-leapstone-2', amount=12),
            Material(item_id='basic-oreha-fusion-material-2', amount=8),
            Material(item_id='silver', amount=25240),
            Material(item_id='gold', amount=170),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=21,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=42,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=125,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=750,
        book_id='tailoring-applied-mending-4',
    ),
    HoningLevel(
        base_item_level=1400,
        next_item_level=1405,
        tier=3,
        base_level=12,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=1500,
        cost=(
            Material(item_id='guardian-stone-crystal-0', amount=592),
            Material(item_id='honor-shard', amount=158),
            Material(item_id='great-honor-leapstone-2', amount=12),
            Material(item_id='basic-oreha-fusion-material-2', amount=8),
            Material(item_id='silver', amount=25860),
            Material(item_id='gold', amount=170),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=21,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=42,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=125,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=750,
        book_id='tailoring-applied-mending-4',
    ),
    HoningLevel(
        base_item_level=1405,
        next_item_level=1410,
        tier=3,
        base_level=13,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=1500,
        cost=(
            Material(item_id='guardian-stone-crystal-0', amount=592),
            Material(item_id='honor-shard', amount=158),
            Material(item_id='great-honor-leapstone-2', amount=12),
            Material(item_id='basic-oreha-fusion-material-2', amount=8),
            Material(item_id='silver', amount=26500),
            Material(item_id='gold', amount=170),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=21,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=42,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=125,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=750,
        book_id='tailoring-applied-mending-4',
    ),
    HoningLevel(
        base_item_level=1410,
        next_item_level=1415,
        tier=3,
        base_level=14,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=1000,
        cost=(
            Material(item_id='guardian-stone-crystal-0', amount=592),
            Material(item_id='honor-shard', amount=158),
            Material(item_id='great-honor-leapstone-2', amount=12),
            Material(item_id='basic-oreha-fusion-material-2', amount=8),
            Material(item_id='silver', amount=27160),
            Material(item_id='gold', amount=180),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=14,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=28,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=83,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=500,
        book_id='tailoring-applied-mending-4',
    ),
    HoningLevel(
        base_item_level=1415,
        next_item_level=1430,
        tier=3,
        base_level=15,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=1000,
        cost=(
            Material(item_id='guardian-stone-crystal-0', amount=686),
            Material(item_id='honor-shard', amount=216),
            Material(item_id='great-honor-leapstone-2', amount=14),
            Material(item_id='basic-oreha-fusion-material-2', amount=10),
            Material(item_id='silver', amount=27820),
            Material(item_id='gold', amount=210),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=14,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=28,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=83,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=500,
    ),
    HoningLevel(
        base_item_level=1430,
        next_item_level=1445,
        tier=3,
        base_level=16,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=1000,
        cost=(
            Material(item_id='guardian-stone-crystal-0', amount=686),
            Material(item_id='honor-shard', amount=292),
            Material(item_id='great-honor-leapstone-2', amount=16),
            Material(item_id='basic-oreha-fusion-material-2', amount=10),
            Material(item_id='silver', amount=28420),
            Material(item_id='gold', amount=250),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=14,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=28,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=83,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=500,
    ),
    HoningLevel(
        base_item_level=1445,
        next_item_level=1460,
        tier=3,
        base_level=17,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=500,
        cost=(
            Material(item_id='guardian-stone-crystal-0', amount=686),
            Material(item_id='honor-shard', amount=292),
            Material(item_id='great-honor-leapstone-2', amount=16),
            Material(item_id='basic-oreha-fusion-material-2', amount=12),
            Material(item_id='silver', amount=29040),
            Material(item_id='gold', amount=280),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=5,
                        max_amount=36),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=9,
                        max_amount=18),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=28,
                        max_amount=6),
        ),
        max_enhancement_rate_permyria=500,
    ),
    HoningLevel(
        base_item_level=1460,
        next_item_level=1475,
        tier=3,
        base_level=18,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=500,
        cost=(
            Material(item_id='guardian-stone-crystal-0', amount=780),
            Material(item_id='honor-shard', amount=536),
            Material(item_id='great-honor-leapstone-2', amount=18),
            Material(item_id='basic-oreha-fusion-material-2', amount=12),
            Material(item_id='silver', amount=29660),
            Material(item_id='gold', amount=320),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=5,
                        max_amount=36),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=9,
                        max_amount=18),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=28,
                        max_amount=6),
        ),
        max_enhancement_rate_permyria=500,
    ),
    HoningLevel(
        base_item_level=1475,
        next_item_level=1490,
        tier=3,
        base_level=19,
        equipment_type=EquipmentType.ARMOR,
        base_rate_permyria=300,
        cost=(
            Material(item_id='guardian-stone-crystal-0', amount=780),
            Material(item_id='honor-shard', amount=728),
            Material(item_id='great-honor-leapstone-2', amount=20),
            Material(item_id='basic-oreha-fusion-material-2', amount=14),
            Material(item_id='silver', amount=30320),
            Material(item_id='gold', amount=350),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=3,
                        max_amount=36),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=6,
                        max_amount=18),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=17,
                        max_amount=6),
        ),
        max_enhancement_rate_permyria=300,
    ),
    HoningLevel(
        base_item_level=1370,
        next_item_level=1375,
        tier=3,
        base_level=6,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=6000,
        cost=(
            Material(item_id='destruction-stone-crystal-0', amount=672),
            Material(item_id='honor-shard', amount=156),
            Material(item_id='great-honor-leapstone-2', amount=12),
            Material(item_id='basic-oreha-fusion-material-2', amount=6),
            Material(item_id='silver', amount=31920),
            Material(item_id='gold', amount=320),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=167,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=333,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=1000,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=4000,
        book_id='tailoring-applied-mending-4',
    ),
    HoningLevel(
        base_item_level=1375,
        next_item_level=1380,
        tier=3,
        base_level=7,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=4500,
        cost=(
            Material(item_id='destruction-stone-crystal-0', amount=672),
            Material(item_id='honor-shard', amount=156),
            Material(item_id='great-honor-leapstone-2', amount=14),
            Material(item_id='basic-oreha-fusion-material-2', amount=6),
            Material(item_id='silver', amount=32700),
            Material(item_id='gold', amount=320),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=125,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=250,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=750,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=4500,
        book_id='tailoring-applied-mending-4',
    ),
    HoningLevel(
        base_item_level=1380,
        next_item_level=1385,
        tier=3,
        base_level=8,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=3000,
        cost=(
            Material(item_id='destruction-stone-crystal-0', amount=672),
            Material(item_id='honor-shard', amount=156),
            Material(item_id='great-honor-leapstone-2', amount=14),
            Material(item_id='basic-oreha-fusion-material-2', amount=8),
            Material(item_id='silver', amount=33520),
            Material(item_id='gold', amount=320),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=84,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=167,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=500,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=3000,
        book_id='tailoring-applied-mending-4',
    ),
    HoningLevel(
        base_item_level=1385,
        next_item_level=1390,
        tier=3,
        base_level=9,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=3000,
        cost=(
            Material(item_id='destruction-stone-crystal-0', amount=830),
            Material(item_id='honor-shard', amount=192),
            Material(item_id='great-honor-leapstone-2', amount=16),
            Material(item_id='basic-oreha-fusion-material-2', amount=8),
            Material(item_id='silver', amount=34340),
            Material(item_id='gold', amount=320),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=84,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=167,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=500,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=3000,
        book_id='tailoring-applied-mending-4',
    ),
    HoningLevel(
        base_item_level=1390,
        next_item_level=1395,
        tier=3,
        base_level=10,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=3000,
        cost=(
            Material(item_id='destruction-stone-crystal-0', amount=830),
            Material(item_id='honor-shard', amount=192),
            Material(item_id='great-honor-leapstone-2', amount=16),
            Material(item_id='basic-oreha-fusion-material-2', amount=8),
            Material(item_id='silver', amount=35180),
            Material(item_id='gold', amount=330),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=84,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=167,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=500,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=3000,
        book_id='tailoring-applied-mending-4',
    ),
    HoningLevel(
        base_item_level=1395,
        next_item_level=1400,
        tier=3,
        base_level=11,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=1500,
        cost=(
            Material(item_id='destruction-stone-crystal-0', amount=830),
            Material(item_id='honor-shard', amount=192),
            Material(item_id='great-honor-leapstone-2', amount=18),
            Material(item_id='basic-oreha-fusion-material-2', amount=8),
            Material(item_id='silver', amount=36040),
            Material(item_id='gold', amount=330),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=21,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=42,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=125,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=750,
        book_id='tailoring-applied-mending-4',
    ),
    HoningLevel(
        base_item_level=1400,
        next_item_level=1405,
        tier=3,
        base_level=12,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=1500,
        cost=(
            Material(item_id='destruction-stone-crystal-0', amount=968),
            Material(item_id='honor-shard', amount=228),
            Material(item_id='great-honor-leapstone-2', amount=18),
            Material(item_id='basic-oreha-fusion-material-2', amount=10),
            Material(item_id='silver', amount=36940),
            Material(item_id='gold', amount=330),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=21,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=42,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=125,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=750,
        book_id='tailoring-applied-mending-4',
    ),
    HoningLevel(
        base_item_level=1405,
        next_item_level=1410,
        tier=3,
        base_level=13,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=1500,
        cost=(
            Material(item_id='destruction-stone-crystal-0', amount=968),
            Material(item_id='honor-shard', amount=228),
            Material(item_id='great-honor-leapstone-2', amount=20),
            Material(item_id='basic-oreha-fusion-material-2', amount=10),
            Material(item_id='silver', amount=37840),
            Material(item_id='gold', amount=330),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=21,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=42,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=125,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=750,
        book_id='tailoring-applied-mending-4',
    ),
    HoningLevel(
        base_item_level=1410,
        next_item_level=1415,
        tier=3,
        base_level=14,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=1000,
        cost=(
            Material(item_id='destruction-stone-crystal-0', amount=968),
            Material(item_id='honor-shard', amount=228),
            Material(item_id='great-honor-leapstone-2', amount=20),
            Material(item_id='basic-oreha-fusion-material-2', amount=10),
            Material(item_id='silver', amount=38760),
            Material(item_id='gold', amount=330),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=14,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=28,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=83,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=500,
        book_id='tailoring-applied-mending-4',
    ),
    HoningLevel(
        base_item_level=1415,
        next_item_level=1430,
        tier=3,
        base_level=15,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=1000,
        cost=(
            Material(item_id='destruction-stone-crystal-0', amount=1144),
            Material(item_id='honor-shard', amount=310),
            Material(item_id='great-honor-leapstone-2', amount=22),
            Material(item_id='basic-oreha-fusion-material-2', amount=12),
            Material(item_id='silver', amount=39720),
            Material(item_id='gold', amount=410),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=14,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=28,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=83,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=500,
    ),
    HoningLevel(
        base_item_level=1430,
        next_item_level=1445,
        tier=3,
        base_level=16,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=1000,
        cost=(
            Material(item_id='destruction-stone-crystal-0', amount=1144),
            Material(item_id='honor-shard', amount=422),
            Material(item_id='great-honor-leapstone-2', amount=24),
            Material(item_id='basic-oreha-fusion-material-2', amount=14),
            Material(item_id='silver', amount=40580),
            Material(item_id='gold', amount=480),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=14,
                        max_amount=12),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=28,
                        max_amount=6),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=83,
                        max_amount=2),
        ),
        max_enhancement_rate_permyria=500,
    ),
    HoningLevel(
        base_item_level=1445,
        next_item_level=1460,
        tier=3,
        base_level=17,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=500,
        cost=(
            Material(item_id='destruction-stone-crystal-0', amount=1144),
            Material(item_id='honor-shard', amount=572),
            Material(item_id='great-honor-leapstone-2', amount=28),
            Material(item_id='basic-oreha-fusion-material-2', amount=16),
            Material(item_id='silver', amount=41460),
            Material(item_id='gold', amount=540),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=5,
                        max_amount=36),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=9,
                        max_amount=18),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=28,
                        max_amount=6),
        ),
        max_enhancement_rate_permyria=500,
    ),
    HoningLevel(
        base_item_level=1460,
        next_item_level=1475,
        tier=3,
        base_level=18,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=500,
        cost=(
            Material(item_id='destruction-stone-crystal-0', amount=1300),
            Material(item_id='honor-shard', amount=776),
            Material(item_id='great-honor-leapstone-2', amount=30),
            Material(item_id='basic-oreha-fusion-material-2', amount=18),
            Material(item_id='silver', amount=42360),
            Material(item_id='gold', amount=640),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=5,
                        max_amount=36),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=9,
                        max_amount=18),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=28,
                        max_amount=6),
        ),
        max_enhancement_rate_permyria=500,
    ),
    HoningLevel(
        base_item_level=1475,
        next_item_level=1490,
        tier=3,
        base_level=19,
        equipment_type=EquipmentType.WEAPON,
        base_rate_permyria=300,
        cost=(
            Material(item_id='destruction-stone-crystal-0', amount=1300),
            Material(item_id='honor-shard', amount=1054),
            Material(item_id='great-honor-leapstone-2', amount=32),
            Material(item_id='basic-oreha-fusion-material-2', amount=20),
            Material(item_id='silver', amount=43260),
            Material(item_id='gold', amount=730),
        ),
        enhancements=(
            Enhancement(item_id='solar-grace-1',
                        rate_increase_permyria=3,
                        max_amount=36),
            Enhancement(item_id='solar-blessing-2',
                        rate_increase_permyria=6,
                        max_amount=18),
            Enhancement(item_id='solar-protection-3',
                        rate_increase_permyria=17,
                        max_amount=6),
        ),
        max_enhancement_rate_permyria=300,
    ),
)

HONES_DICT = {(h.base_item_level, h.equipment_type): h for h in HONES}
