SHOULD_HIDE_COMMAND_OUTPUT = {
    "add_punch_message": True,
    "add_role": True,
    "calendar": False,
    "change_time": True,
    "compliment": False,
    "git": True,
    "price": False,
    "hone": True,
    "mari": False,
    "remove_role": True,
    "role_selector": False,
    "make_raid": False,
    "punch": False,
    "see_signups": True,
    "report": False,
    "server_status": True,
    "maintenance_watch": True,
    "vote": False,
}
