name: deploy Python to lambda
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy code to handler Lambda
      uses: qubitro/action-lambda-python-zip@v1.0
      with:
        lambda_layer_arn: 'arn:aws:lambda:us-east-2:391107963258:layer:robotrader-deps'
        lambda_function_name: 'robotrader'
        lambda_region: 'us-east-2'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        SERVER_ID: ${{ secrets.SERVER_ID }}
    - name: Deploy code to dispatcher Lambda
      uses: qubitro/action-lambda-python-zip@v1.0
      with:
        lambda_layer_arn: 'arn:aws:lambda:us-east-2:391107963258:layer:robotrader-deps'
        lambda_function_name: 'trader_dispatcher'
        lambda_region: 'us-east-2'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
    - name: Upload commands to S3 
      uses: tpaschalis/s3-sync-action@master
      env:
       FILE: ./commands/commands.json
       AWS_REGION: ${{ secrets.AWS_REGION }}
       AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       SERVER_ID: ${{ secrets.SERVER_ID }}
  publish:
    needs: build
    if: needs.build.result == 'success'
    runs-on: ubuntu-latest
    steps:
    - name: Publish commands
      uses: actions/checkout@master
    - name: Install Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Publish slash commands to Discord
      env: 
        APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
        TEST_SERVERS: ${{ secrets.TEST_SERVERS }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
          output=$(python scripts/publish_commands.py)
          echo "::set-output name=publishStatus::$output"
      id: step1
    - name: Print status
      run: echo "${{ steps.step1.outputs.publishStatus }}"
